# .github/workflows/daily-brief-workflow.yml

name: Generate Daily Market Briefing (AM & PM)

on:
  schedule:
    # รันรอบเช้า (AM) ตอน 01:00 UTC (8:00 น. เวลาไทย)
    - cron: '0 1 * * *'
    # รันรอบบ่าย (PM) ตอน 07:00 UTC (14:00 น. เวลาไทย)
    - cron: '0 7 * * *'

  workflow_dispatch:
    inputs:
      period:
        description: 'Run for a specific period (AM/PM)'
        required: true
        type: choice
        options:
          - AM
          - PM

jobs:
  generate-briefing:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # ถ้าเป็นการรันตามเวลา (schedule) ให้ปล่อยว่าง
        # ถ้าเป็นการรันด้วยมือ (workflow_dispatch) ให้ใช้ค่าที่เลือก
        period: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.period)) || fromJSON('[]') }}

    steps:
      - name: Determine Period for Scheduled Run
        id: get_period
        # ถ้าเป็นการรันตามเวลา (schedule) ให้เช็คเวลาปัจจุบัน (UTC hour)
        # ถ้าเป็นชั่วโมงที่ 1 (รอบเช้า) ให้ตั้ง period=AM, นอกนั้นเป็น PM
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            current_hour=$(date -u +'%H')
            if [ "$current_hour" -eq 1 ]; then
              echo "period=AM" >> $GITHUB_OUTPUT
            else
              echo "period=PM" >> $GITHUB_OUTPUT
            fi
          else
            # ถ้าเป็นการรันด้วยมือ ให้ใช้ค่าจาก matrix
            echo "period=${{ matrix.period }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Briefing Worker for ${{ steps.get_period.outputs.period }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        # ส่ง Argument (AM หรือ PM) ต่อท้ายคำสั่ง
        run: python worker_daily_brief.py ${{ steps.get_period.outputs.period }}