name: Generate Daily Market Briefing (AM & PM)

on:
  schedule:
    # รันรอบเช้า (AM) ตอน 00:05 UTC (7:05 น. เวลาไทย)
    - cron: '5 0 * * *'
    # รันรอบบ่าย (PM) ตอน 05:05 UTC (13:05 น. เวลาไทย)
    - cron: '5 6 * * *'

  workflow_dispatch:
    inputs:
      period:
        description: 'Run for a specific period (AM/PM)'
        required: true
        type: choice
        options:
          - AM
          - PM

jobs:
  generate-briefing:
    runs-on: ubuntu-latest

    steps:
      ### START: ส่วนที่แก้ไข ###
      # แก้ไข Step นี้เพื่อเพิ่มความแม่นยำ
      - name: Determine Period
        id: get_period
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            # ตรวจสอบว่า workflow ถูก trigger จาก cron string ไหนโดยตรง
            # วิธีนี้แม่นยำ 100% ไม่ว่า job จะดีเลย์ไปนานแค่ไหนก็ตาม
            if [ "${{ github.event.schedule }}" == "5 0 * * *" ]; then
              echo "period=AM" >> $GITHUB_OUTPUT
            else
              # ถ้าไม่ใช่ schedule ของรอบเช้า ก็ถือว่าเป็นรอบบ่าย
              echo "period=PM" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # ส่วนนี้สำหรับรันด้วยมือ ยังคงทำงานเหมือนเดิม
            echo "period=${{ github.event.inputs.period }}" >> $GITHUB_OUTPUT
          fi
      ### END: ส่วนที่แก้ไข ###

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Briefing Worker for ${{ steps.get_period.outputs.period }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python worker_daily_brief.py ${{ steps.get_period.outputs.period }}
