# .github/workflows/daily-brief-workflow.yml (ฉบับแก้ไขเวลา)

name: Generate Daily Market Briefing (AM & PM)

on:
  schedule:
    # รันรอบเช้า (AM) ตอน 23:00 UTC (6:00 น. เวลาไทย)
    - cron: '0 23 * * *'
    # รันรอบบ่าย (PM) ตอน 05:00 UTC (12:00 น. เวลาไทย)
    - cron: '0 5 * * *'

  workflow_dispatch:
    inputs:
      period:
        description: 'Run for a specific period (AM/PM)'
        required: true
        type: choice
        options:
          - AM
          - PM

jobs:
  generate-briefing:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Period
        id: get_period
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            current_hour=$(date -u +'%H')
            # ตรวจสอบเวลาที่แก้ไขใหม่:
            # ถ้าเป็นชั่วโมงที่ 23 (UTC) คือรอบเช้า (AM)
            if [ "$current_hour" -eq 23 ]; then
              echo "period=AM" >> $GITHUB_OUTPUT
            else
              # นอกนั้น (คือชั่วโมงที่ 5) เป็นรอบบ่าย (PM)
              echo "period=PM" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "period=${{ github.event.inputs.period }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Briefing Worker for ${{ steps.get_period.outputs.period }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python worker_daily_brief.py ${{ steps.get_period.outputs.period }}