name: Generate Daily Market Briefing

on:
  # 1. ตั้งเวลาให้รันทุกวันตอน 01:00 UTC (ซึ่งคือ 8:00 น. ตามเวลาประเทศไทย)
  schedule:
    - cron: '0 1 * * *' # Runs at 01:00 UTC daily

  # 2. อนุญาตให้รัน Manual ได้จากหน้า Actions tab
  workflow_dispatch:

jobs:
  generate-briefing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # หรือเวอร์ชันที่คุณใช้

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ติดตั้ง library ที่จำเป็นสำหรับสคริปต์นี้
          pip install python-dotenv groq firebase-admin google-cloud-firestore

      - name: Run Daily Briefing Worker
        env:
          # ดึงค่า Secrets มาใส่ใน Environment Variables
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python worker_daily_brief.py